[profile.default]
src = "src"
out = "out"
test = "test"
script = "script"
libs = ["lib"]
solc_version = "0.8.24"
evm_version = "cancun"
optimizer = true
optimizer_runs = 10000
via_ir = false
ffi = false

[profile.default.fuzz]
runs = 1000
max_test_rejects = 65536

[profile.default.fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

[rpc_endpoints]
monad_testnet = "https://testnet-rpc.monad.xyz"

[etherscan]
monad_testnet = { key = "", chain = 10143, url = "https://testnet.monadscan.com/api" }
